教科書/aiapps/aiapps/urls.py
from django.contrib import admin
from django.urls import path, include
# import carbike.views as carbike

urlpatterns = [
    path('admin/', admin.site.urls),
    path('carbike/', include('carbike.urls')),
]

教科書/aiapps/carbike/urls.py
from django.urls import path

from . import views

app_name ='carbike'
urlpatterns = [
    path('', views.index, name='index'),
    path('predict/', views.predict, name='predict'),
]

教科書/aiapps/carbike/models.py
from django.db import models

import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import load_model
from PIL import Image
import io, base64

graph = tf.get_default_graph()

class Photo(models.Model):
    image = models.ImageField(upload_to='photos')

    IMAGE_SIZE = 224 # 画像サイズ
    MODEL_FILE_PATH = './carbike/ml_models/vgg16_transfer.h5' # モデルファイル
    classes = ["car", "motorbike"]
    num_classes = len(classes)

    # 引数から画像ファイルを参照して読み込む
    def predict(self):
        model = None
        global graph
        with graph.as_default():
            model = load_model(self.MODEL_FILE_PATH)

            img_data = self.image.read()
            img_bin = io.BytesIO(img_data)

            image = Image.open(img_bin)
            image = image.convert("RGB")
            image = image.resize((self.IMAGE_SIZE, self.IMAGE_SIZE))
            data = np.asarray(image) / 255.0
            X = []
            X.append(data)
            X = np.array(X)

            result = model.predict([X])[0]
            predicted = result.argmax()
            percentage = int(result[predicted] * 100)

            # print(self.classes[predicted], percentage)
            return self.classes[predicted], percentage

    def image_src(self):
        with self.image.open() as img:
            base64_img = base64.b64encode(img.read()).decode()

            return 'data:' + img.file.content_type + ';base64,' + base64_img

教科書/aiapps/carbike/forms.py
from django import forms

class PhotoForm(forms.Form):
    image = forms.ImageField(widget=forms.FileInput(attrs={'class':'custom-file-input'}))

教科書/aiapps/carbike/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from .forms import PhotoForm
from .models import Photo

def index(request):
    template = loader.get_template('carbike/index.html')
    context = {'form': PhotoForm()}
    return HttpResponse(template.render(context, request))

def predict(request):
    if not request.method == 'POST':
        return
        redirect('carbike:index')

    form = PhotoForm(request.POST, request.FILES)
    if not form.is_valid():
        raise ValueError('Formが不正です')

    photo = Photo(image=form.cleaned_data['image'])
    predicted, percentage = photo.predict()

    template = loader.get_template('carbike/result.html')

    context = {
        'photo_name': photo.image.name,
        'photo_data': photo.image_src(),
        'predicted': predicted,
        'percentage': percentage,
    }

    return HttpResponse(template.render(context, request))

教科書/aiapps/carbike/templates/carbike/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    {% load static %}
    {% load bootstrap4 %}
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'carbike/css/style.css' %}">
    {% bootstrap_javascript jquery='full' %}
    <title>画像判定AIアプリ | {% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">画像判定AIアプリ</a>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

教科書/aiapps/carbike/templates/carbike/index.html
{% extends 'carbike/base.html' %}
{% block title %}車・バイク推定アプリメニュー{% endblock %}

{% block content %}
<div>
    <h4 class="mt-4 mb-5 border-bottom">車・バイク推定アプリ</h4>
    <p>画像ファイルを選択して推定ボタンをクリックしてください。</p>
    <form action="{% url 'carbike:predict' %}" method="post" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <div class="custom-file">
            {{ form.image }}
            <label class="custom-file-label" for="customFile">
                推定したいファイルを選択してください。
            </label>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">推定する！</button>
    </form> 
</div>
{% endblock %}

教科書/aiapps/carbike/templates/carbike/result.html
{% extends 'carbike/base.html' %}
{% block title %}車・バイク推定結果{% endblock %}

{% block content %}
<div>
    <h4 class="mt-4 mb-5 border-bottom">車・バイク推定結果</h4>

    <table class='table'>
        <tbody>
            <tr>
                <td>ファイル名</td>
                <td>{{ photo_name }}</td>
            </tr>
            <tr>
                <td>画像ファイル</td>
                <td><img class='preview-img' src={{ photo_data }} ></img></td>
                </tr>
            <tr>
                <td>推定ラベル</td>
                <td>{{ predicted }}</td>
            </tr>
            <tr>
                <td>推定確率</td>
                <td>{{ percentage }} %</td>
            </tr>
        </tbody>
    </table>

    <a href = "{% url 'carbike:index' %}" class="btn btn-primary">画像選択メニューに戻る</a>

</div>
{% endblock %}